<?php
namespace WPGPT\MCPBridge;
use WPGPT\MCPBridge\Maintenance\Maintenance_Service;
if ( ! defined( 'ABSPATH' ) ) { exit; }
class Maintenance_Provider extends Base_Ability_Provider {
    private ?Maintenance_Service $service = null;
    public function get_abilities(): array { return array(
        'wpgpt/maintenance-cache-manage'=>array('label'=>__('Maintenance cache manage','wpgpt-mcp-bridge'),'description'=>__('Inspecciona o vacía la caché.','wpgpt-mcp-bridge'),'input_schema'=>array('type'=>'object','properties'=>array('action'=>array('type'=>'string'),'scope'=>array('type'=>'string'))),'execute_callback'=>array($this,'cache_manage'),'output_schema'=>$this->object_schema(),'permission_callback'=>array($this,'can_manage_site')),
        'wpgpt/maintenance-transients-manage'=>array('label'=>__('Maintenance transients manage','wpgpt-mcp-bridge'),'description'=>__('Gestiona transients.','wpgpt-mcp-bridge'),'input_schema'=>array('type'=>'object','properties'=>array('action'=>array('type'=>'string'),'search'=>array('type'=>'string'),'limit'=>array('type'=>'integer'),'keys'=>array('type'=>'array','items'=>array('type'=>'string')))),'execute_callback'=>array($this,'transients_manage'),'output_schema'=>$this->object_schema(),'permission_callback'=>array($this,'can_manage_site')),
        'wpgpt/maintenance-media-regenerate'=>array('label'=>__('Maintenance media regenerate','wpgpt-mcp-bridge'),'description'=>__('Regenera miniaturas de medios.','wpgpt-mcp-bridge'),'input_schema'=>array('type'=>'object','properties'=>array('attachment_ids'=>array('type'=>'array','items'=>array('type'=>'integer')),'limit'=>array('type'=>'integer'),'offset'=>array('type'=>'integer'),'only_missing'=>array('type'=>'boolean'))),'execute_callback'=>array($this,'media_regenerate'),'output_schema'=>$this->object_schema(),'permission_callback'=>array($this,'can_manage_site')),
        'wpgpt/maintenance-search-replace'=>array('label'=>__('Maintenance search replace','wpgpt-mcp-bridge'),'description'=>__('Ejecuta un search/replace seguro.','wpgpt-mcp-bridge'),'input_schema'=>array('type'=>'object','properties'=>array('search'=>array('type'=>'string'),'replace'=>array('type'=>'string'),'tables'=>array('type'=>'array','items'=>array('type'=>'string')),'dry_run'=>array('type'=>'boolean'),'case_sensitive'=>array('type'=>'boolean')),'required'=>array('search','replace')),'execute_callback'=>array($this,'search_replace'),'output_schema'=>$this->object_schema(),'permission_callback'=>array($this,'can_manage_site')),
        'wpgpt/maintenance-mode-set'=>array('label'=>__('Maintenance mode set','wpgpt-mcp-bridge'),'description'=>__('Activa o desactiva el modo mantenimiento.','wpgpt-mcp-bridge'),'input_schema'=>array('type'=>'object','properties'=>array('enabled'=>array('type'=>'boolean'),'message'=>array('type'=>'string')),'required'=>array('enabled')),'execute_callback'=>array($this,'maintenance_mode_set'),'output_schema'=>$this->object_schema(),'permission_callback'=>array($this,'can_manage_site')),
    ); }
    public function cache_manage(array $input){ return $this->service()->cache_manage($input);} public function transients_manage(array $input){ return $this->service()->transients_manage($input);} public function media_regenerate(array $input){ return $this->service()->media_regenerate($input);} public function search_replace(array $input){ return $this->service()->search_replace($input);} public function maintenance_mode_set(array $input){ return $this->service()->maintenance_mode_set($input);} private function service(): Maintenance_Service { return $this->service ??= new Maintenance_Service(); }
}
