<?php
namespace WPGPT\MCPBridge;
use WPGPT\MCPBridge\WooCommerce\WooCommerce_Service;
if ( ! defined( 'ABSPATH' ) ) { exit; }
class WooCommerce_Provider extends Base_Ability_Provider {
    private ?WooCommerce_Service $service = null;
    public function get_abilities(): array { return array(
        'wpgpt/wc-resource-query'=>array('label'=>__('WC resource query','wpgpt-mcp-bridge'),'description'=>__('Consulta recursos WooCommerce.','wpgpt-mcp-bridge'),'input_schema'=>$this->query_schema(),'execute_callback'=>array($this,'resource_query'),'output_schema'=>$this->object_schema(),'permission_callback'=>array($this,'can_manage_site')),
        'wpgpt/wc-resource-get'=>array('label'=>__('WC resource get','wpgpt-mcp-bridge'),'description'=>__('Obtiene un recurso WooCommerce.','wpgpt-mcp-bridge'),'input_schema'=>array('type'=>'object','properties'=>array('resource'=>array('type'=>'string'),'id'=>array('type'=>'integer')),'required'=>array('resource','id')),'execute_callback'=>array($this,'resource_get'),'output_schema'=>$this->object_schema(),'permission_callback'=>array($this,'can_manage_site')),
        'wpgpt/wc-resource-upsert'=>array('label'=>__('WC resource upsert','wpgpt-mcp-bridge'),'description'=>__('Crea o actualiza un recurso WooCommerce.','wpgpt-mcp-bridge'),'input_schema'=>array('type'=>'object','properties'=>array('resource'=>array('type'=>'string'),'id'=>array('type'=>'integer'),'data'=>array('type'=>'object','additionalProperties'=>true)),'required'=>array('resource','data')),'execute_callback'=>array($this,'resource_upsert'),'output_schema'=>$this->object_schema(),'permission_callback'=>array($this,'can_manage_site')),
        'wpgpt/wc-order-action'=>array('label'=>__('WC order action','wpgpt-mcp-bridge'),'description'=>__('Aplica una acción a un pedido WooCommerce.','wpgpt-mcp-bridge'),'input_schema'=>array('type'=>'object','properties'=>array('order_id'=>array('type'=>'integer'),'action'=>array('type'=>'string'),'params'=>array('type'=>'object','additionalProperties'=>true)),'required'=>array('order_id','action')),'execute_callback'=>array($this,'order_action'),'output_schema'=>$this->object_schema(),'permission_callback'=>array($this,'can_manage_site')),
        'wpgpt/wc-report-summary'=>array('label'=>__('WC report summary','wpgpt-mcp-bridge'),'description'=>__('Genera un resumen de WooCommerce.','wpgpt-mcp-bridge'),'input_schema'=>array('type'=>'object','properties'=>array('report'=>array('type'=>'string'),'date_from'=>array('type'=>'string'),'date_to'=>array('type'=>'string'),'limit'=>array('type'=>'integer')),'required'=>array('report')),'execute_callback'=>array($this,'report_summary'),'output_schema'=>$this->object_schema(),'permission_callback'=>array($this,'can_manage_site')),
    ); }
    public function resource_query(array $input){ return $this->service()->resource_query($input);} public function resource_get(array $input){ return $this->service()->resource_get($input);} public function resource_upsert(array $input){ return $this->service()->resource_upsert($input);} public function order_action(array $input){ return $this->service()->order_action($input);} public function report_summary(array $input){ return $this->service()->report_summary($input);} private function service(): WooCommerce_Service { return $this->service ??= new WooCommerce_Service(); }
    private function query_schema(): array { return array('type'=>'object','properties'=>array('resource'=>array('type'=>'string'),'filters'=>array('type'=>'object','additionalProperties'=>true),'search'=>array('type'=>'string'),'page'=>array('type'=>'integer'),'per_page'=>array('type'=>'integer'),'orderby'=>array('type'=>'string'),'order'=>array('type'=>'string')),'required'=>array('resource')); }
}
